### ISSUE TITLE
Add option to skip file I/O, staging, and committing of version changes

### ISSUE THREAD

**Issue by as3mbus** [reeseschultz/ubump#12]
is it possible to extract the functionality to just add tags and and push for the existing package. i felt like it's too complex to use ubump if i only need to bump the version for newly created package that previously got added manually.

also would be nice if i have the same function to just make all branch of a package from master branch

**Comment by reeseschultz** [comment]
> is it possible to extract the functionality to just add tags and and push for the existing package.

That is possible.

Presently, ubump's interative CLI is subtractive, e.g. "skip tagging" or "skip internal referencing synchronization." This is to emphasize convention over configuration, since I believe most users would want all of that based on the workflows of similar releasing tools I've observed in the Node ecosystem.

To do what you're wanting, I would extend the interactive CLI with additional options, likely that would need to be passed to a `compose` command. That naming makes sense to me since you would compose only the actions you want, such as tagging and pushing as you mentioned. Does that approach sound good to you?

> would be nice if i have the same function to just make all branch of a package from master branch

Can you clarify that suggestion?

**Comment by as3mbus** [comment]
well imo `pack` for split and tagging and/or `publish` for pushing seems to fit my criteria.  but if your view is to arrange an action 'compose' should do just fine . 

my main need for this function is just publishing every package that was made prior to using ubump and pushing the package as is, without any version bumping

>Can you clarify that suggestion?

well the later request is just me neglecting versioning purpose for easier develop version bumping.

but yeah it would supplement the previous request. e.g publishing version `n` that was set up prior to using ubump

**Comment by reeseschultz** [comment]
Okay, I believe I understand what you need.

You've initialized a new package, and ubump's interactive CLI won't let you tag, split, and/or push it since you want to retain the initial version⁠—right now ubump assumes there's "no change" when in reality there is.

Other releasing tools have a common solution to this problem, which is that they provide a manual version entry option⁠. I would prefer to piggyback on other established conventions when possible. So what if we did this: when ubump asks for the type of change desired, there is a *manual* option available that defaults to the current version detected? That would also allow users to change the version to whatever they want, which somebody will probably request at a later point anyway.

**Comment by as3mbus** [comment]
well that's also a good option for doing that. 

i haven't know much about node releasing workflow and keep trying to have more basic functionality available instead of lumping it into bigger function. but that's just me.

**Comment by reeseschultz** [comment]
Upon further inspection, I've decided to simplify the changes requested by providing a `--skip-commit` option for the interactive CLI that, if used, skips staging and committing of version changes for the project and packages. When that option is provided, I'll code ubump to opt for provided or, by default, current versions when tagging.

**Comment by reeseschultz** [comment]
@as3mbus to resolve this sort of problem in the future, users can pass the `--skip-commit` option when running ubump, and additionally specify manual version entry for the project and/or packages in question. The default for manual entry is the current version. After that, the user is solicited to tag with whatever version was requested as long as tagging is enabled. If this doesn't resolve the issue from your perspective, please open a new issue.

Note that the 'no change' option's meaning is preserved--it literally means no change, whether it's for a commit or a tag, hence why manual entry would be needed even if it's for the current version.

Hope all of this helps. I'll look at your other presently open issue when I have time.

**Comment by as3mbus** [comment]
so i am back after couple of month using basic subtree functionality to update my package (and it get tedious). and im still confused on how do i use it in accordance with my workflow. 

> additionally specify manual version entry for the project and/or packages in question

especially for this line. how do i do that ? 

maybe i just have different workflow than usual package developer. 
but here what i've done when updating an package :

1. modify the script 
1. update the changelog 
1. update package.json
1. commit the changes
1. push the changes
1. split the trees
1. push the tree
1. (optionally tagging the changes)

i'd love to use ubump to shorten my chore after `push the changes` part.

feel free to question my workflow. since i am interested in how ubump aim to be used for and what ubump preferred workflow is.

**Comment by reeseschultz** [comment]
@as3mbus for manual entry, you just press the up arrow or `k` on your keyboard, and you'll see a manual entry option for specifying the version. The list wraps around circularly so you may not see it without moving up or down.

So earlier you explained you wanted to retain the original version of a package when releasing it for the first time, hence why I added manual entry (to retain the same version) and the `--skip-commit` option, which will skip straight to tagging.

By default ubump includes >= step 3 as part of its workflow. Options such as `--skip-commit` override that. The [documentation](https://github.com/reeseschultz/ubump#options) extensively explains what such options are and how they work. The convention is skipping defaults. It's [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration). I will not deviate from that standard.

With that said, if ubump isn't working how you want, feel free to submit a PR. As long as you follow the conventions I've established, the code review should go swimmingly.

**Comment by as3mbus** [comment]
alright i tested it and it work fine but issue #11 still quite holding my test :(
