### ISSUE TITLE
feature request: internal references

### ISSUE THREAD

**Issue by favoyang** [reeseschultz/ubump#5]
Can ubump handle package internal references? i.e. For monorepos with `namespace.core.a` and `namespace.module.b`, where `namespace.module.b` depends on `namespace.core.a`. When bumps version, will `namespace.module.b` also bump the the dependency version?

```
namespace.core.a 1.0.0

namespace.module.b 1.0.0
  deps:
    namespace.core.a: 1.0.0
```

bumps => 
```
namespace.core.a 1.0.1

namespace.module.b 1.0.1
  deps:
    namespace.core.a: 1.0.1  <== update internal reference?
```

**Comment by reeseschultz** [comment]
Presently, no, but I'd be happy to add that feature in the coming days.

`ubump` _does_ presently sync dependencies from the `manifest.json`, and I'm actually working on #1 right now, which will sync the editor version from `ProjectSettings/ProjectVersion.txt`.

But yeah, internal references are absolutely possible as well. Shouldn't take me long to implement that. Thanks for bringing this up. If there's anything else you would like to see, please let me know.

**Comment by reeseschultz** [comment]
Sorry for the delay. I've decided I'm going to meet you in the middle with this. Later today I'm adding `sync-internal-refs`/`syncInternalRefs` to the CLI/API. It will also be called (by default) in the *interactive* CLI. It will sync all internal references *after* any bumping has already taken place to be safe specifically for the interactive CLI, but it will never automatically bump the version of a package that had its references updated. That is the only departure from your ask. To me, it's the user's responsibility to decide whether or not a given package itself needs to be bumped and how.

Bumping is basically synonymous with publishing in our case, so in other words I'm saying that internal references are one thing, but "publishing" a package via bumping is an area where I would prefer to tread lightly. And that can happen in a later commit if needed. I hope that still sounds reasonable, because otherwise there are so many ways this could be customized that it makes my brain hurt.

The effect of what I'll implement is this: if `namespace.core.a` is bumped and `namespace.core.b` references it, then `namespace.core.b`'s reference would be updated to reflect the latest `namespace.core.a`. That said, the version of `namespace.core.b` would go unchanged until it itself was specifically commanded to bump by the user. While it may seem on the surface misleading if `namespace.core.b` doesn't get bumped, the flip side is that, well, if the user never has to manually bump it or isn't asked to do so by the interactive CLI, then there's a 99% backward compatibility is still there since nothing changed in that package to account for the change to the reference.

**Comment by favoyang** [comment]
Looks reasonable for me. Thanks for fixing it.

**Comment by reeseschultz** [comment]
You're welcome!
